In [1]:
# Import Dependencies
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
# Sample Sentences
sentences = [
    'I Love my Dog',
    'I Love my Cat',
    'I Love that Dog!',
    'Do you think my dog is amazing?'
]

### Text Tokenization

In [3]:
# Tokenize Text, OOV: Out of Vocabulary, for text in input not in vocabulary
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_idx = tokenizer.word_index
print(word_idx)

{'<OOV>': 1, 'i': 2, 'love': 3, 'my': 4, 'dog': 5, 'cat': 6, 'that': 7, 'do': 8, 'you': 9, 'think': 10, 'is': 11, 'amazing': 12}


### Text to Token Mapping

In [4]:
# List of Sequences i.e. text to number [token] mapping
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 3, 4, 5], [2, 3, 4, 6], [2, 3, 7, 5], [8, 9, 10, 4, 5, 11, 12]]


### Text Padding

In [6]:
# Apply Padding to Text to make all Inputs of Same Size
padded = pad_sequences(sequences, padding='post')
padded

array([[ 2,  3,  4,  5,  0,  0,  0],
       [ 2,  3,  4,  6,  0,  0,  0],
       [ 2,  3,  7,  5,  0,  0,  0],
       [ 8,  9, 10,  4,  5, 11, 12]], dtype=int32)

In [7]:
# Apply Padding to Text to make all Inputs of Same Size
# maxlen: Limit the Size of the Sequence by
padded = pad_sequences(sequences, padding='post', maxlen=5)
padded

array([[ 2,  3,  4,  5,  0],
       [ 2,  3,  4,  6,  0],
       [ 2,  3,  7,  5,  0],
       [10,  4,  5, 11, 12]], dtype=int32)

In [8]:
# Applying maxlen makes us lose the text encodings outside the size range
# We can define where to lose the text from i.e starting or ending of sentence
# maxlen: Limit the Size of the Sequence by
padded = pad_sequences(sequences, padding='post', maxlen=5, truncating='post')
padded

array([[ 2,  3,  4,  5,  0],
       [ 2,  3,  4,  6,  0],
       [ 2,  3,  7,  5,  0],
       [ 8,  9, 10,  4,  5]], dtype=int32)

### Testing the Tokeinizer on New Text

In [10]:
# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq, maxlen=10, padding='post')
print("\nPadded Test Sequence: ")
print(padded)


Test Sequence =  [[2, 1, 3, 4, 5], [4, 5, 1, 4, 1]]

Padded Test Sequence: 
[[2 1 3 4 5 0 0 0 0 0]
 [4 5 1 4 1 0 0 0 0 0]]


In the above test example, since the words "really" in the first sentence and "loves" in the second sentence were not a part of the vocabulary, hence in the padded sequence they have an encoding of "1" i.e "< OOV >"